AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  CargoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda/cargo-lambda-prototype/
      Events:
        CargoLambdaEvent:
          Type: HttpApi
      Handler: rust.handler
      Runtime: provided.al2023
Outputs:
  CargoLambdaHttpApiUrl:
    Description: URL of the Cargo-Lambda Prototype HTTP API endpoint
    Value:
      Fn::Sub: "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
