AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  CargoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda/cargo-lambda-prototype/
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
      Handler: rust.handler
      Runtime: provided.al2023
Outputs:
  FunctionUrl:
    Value: !GetAtt CargoLambdaFunctionUrl.FunctionUrl
    Export:
      Name: FunctionUrl
